CREATE TABLE `client` (
`client_id` int(11) NOT NULL auto_increment,
`login_id` int(11)  NULL,
`guardian_user_id` int(11)  NULL,
`name_of_guardian` varchar(111) default NULL,
`firstname` varchar(50) default NULL,
`lastname` varchar(50) default NULL,
`birthday` date default NULL,
`address` varchar(50) default NULL,
`city` varchar(50) default NULL,
`state_code` varchar(3) default NULL,
`zip` varchar(20) default NULL,
`email` varchar(50) default NULL,
`phone` varchar(50) default NULL,
`cellphone` varchar(50) default NULL,
`business_phone` varchar(50) default NULL,
`business_address` varchar(50) default NULL,
`business_state_code` varchar(50) default NULL,
`business_zip` varchar(10) default NULL,
`social_security_number` varchar(50) default NULL,
`insurance1_type_id` int(11) default NULL,
`insurance1` varchar(50) default NULL,
`insurance1_number` varchar(50) default NULL,
`insurance2_type_id` int(11) default NULL,
`insurance2` varchar(50) default NULL,
`insurance2_number` varchar(50) default NULL,
`referred_by` varchar(50) default NULL,
`why_visiting` text,
`employed_by` varchar(50) default NULL,
`marital_status` int(11) default NULL,
`emergency_contact_name` varchar(60) default NULL,
`emergency_phone` varchar(50) default NULL,
`emergency_cellphone` varchar(50) default NULL,
`is_active` tinyint(1) default NULL,
`date_created` datetime default NULL,
`date_lastvisited` datetime default NULL,
PRIMARY KEY (`client_id`)
) ;




CREATE TABLE `office` (
`office_id` int(11) NOT NULL auto_increment,
`login_id` int(11) default NULL,
`office_name` varchar(50) default NULL,
`subdomain` varchar(50) default NULL,
`address` varchar(50) default NULL,
`city` varchar(50) default NULL,
`state_code` varchar(3) default NULL,
`zip` varchar(20) default NULL,
`email` varchar(50) default NULL,
`phone` varchar(50) default NULL,
`timezone_id` int(11) default NULL,
`contact_info` varchar(50) default NULL,
`doctor_number` varchar(50) default NULL,
`staff_number` varchar(50) default NULL,
`patients_per_day` varchar(50) default NULL,
`scheduling_unit_size` int(11) default NULL,
`hours_open` varchar(50) default NULL,
`days_open` varchar(50) default NULL,
`midday_closed` varchar(50) default NULL,
`holidays` varchar(50) default NULL,
`call_type_id` int(11) default NULL,
`is_office` varchar(1) default NULL,
`is_active` tinyint(1) default NULL,
`date_created` datetime default NULL,
`date_lastvisited` datetime default NULL,
`visitcount` int(11) default NULL,
`office_text` text,
`first_email` int(11) default NULL,
`second_email` int(11) default NULL,
`third_email` int(11) default NULL,
`first_phonecall` int(11) default NULL,
`second_phonecall` int(11) default NULL,
`third_phonecall` int(11) default NULL,
`phonecall_time` int(11) default NULL,
PRIMARY KEY (`office_id`)
) ;


CREATE TABLE `login` (
`login_id` int(11) NOT NULL auto_increment,
`password` varchar(50) default NULL,
`username` varchar(150) default NULL,
`is_active` tinyint(1) default NULL,
PRIMARY KEY (`login_id`)
) 